### ISSUE TITLE
Convert to relative paths

### ISSUE THREAD

**Issue by brandonhackney** [VPNLirvine/trEYEcopa#1]
Basically everything is currently hardcoded to look in /Users/vpnl/Documents/MATLAB/. Proposed fix:

- [x] Get a list of every place that path is specified, and where it's pointing to.
- [x] Ensure that the path targets do actually exist on this repo 😅 and if not, push them in
- [x] Write a function that starts with pwd and defines all other required paths relative to that.
- [x] Update existing path references to implement the new function

For example, you could have a function pths = specifyPaths() that says:
pths.base = pwd;
pths.stim = fullfile(pths.base, 'stims');
etc.

Stretch goal: remove all uses of cd(), replacing them with e.g. addpath() or fullfile() as needed.

**Comment by VPNLirvine** [comment]
Functions that hardcode paths:
frame2movie_2
frame2movie_3
frameGenerator
histPerStim
osfImport
plotCrossFixations
srImport
Ttest

Targets:
/frames
/Martin Weisberg stims
Cd /ExpAnalyze (frameGenerator line 47)
/MWoutput
/ExpOutputs
/fixation_checks
Cd /edfImport (osfImport line 29)
/TCoutput
Cd /edf_alt (srimpoht line 20)
Cd /ExpAnalyze (srimpoht line 23)

**Comment by brandonhackney** [comment]
frame2movie is missing the folder of frames, which currently exists at `/Users/vpnl/Documents/MATLAB/frames`. Is there a function that generates the frames from the movies, though? Because we have the movies.

**Comment by brandonhackney** [comment]
histPerStim AND osfImport are both looking for `/Users/vpnl/Documents/MATLAB/ExpOutputs/MWoutput`, which is where the .edf files exist. We don't want that data in the repo, but we at least need them on OSF or something for testing.

**Comment by brandonhackney** [comment]
> frame2movie is missing the folder of frames, which currently exists at `/Users/vpnl/Documents/MATLAB/frames`. Is there a function that generates the frames from the movies, though? Because we have the movies.

Yes, frameGenerator. frame2movie now also calls frameGenerator if the required folder of frames doesn't exist.

**Comment by brandonhackney** [comment]
Also need to upload `/edf_alt/` to use `srImport()`

**Comment by brandonhackney** [comment]
stretch goal achieved! only two or three instances of `cd()` left for the purposes of using mex files.
