### ISSUE TITLE
Allow early termination

### ISSUE THREAD

**Issue by VPNLirvine** [VPNLirvine/trEYEcopa#10]
Need to add some method for breaking out of the experiment early. Currently, using the Esc button just sends you back to eyetracker calibration. We need to use a different key to terminate entirely, and add decide where to add that check (ie during video playback? During drift correct?)

**Comment by brandonhackney** [comment]
Done, see [this commit](https://github.com/VPNLirvine/trEYEcopa/commit/4dec435d3baa64a447c8f435f38d6255108f4ac0)
