### ISSUE TITLE
Change appearance of calibration target

### ISSUE THREAD

**Issue by brandonhackney** [VPNLirvine/trEYEcopa#19]
The standard calibration and drift correction target is a filled circle (for peripheral detectability) with a central "hole" target (for accurate fixation). The sizes of these features may be set with `set_target_size(diameter, holesize)`. If `holesize` is 0, no central feature will be drawn. The disk is drawn in the calibration foreground color, and the hole is drawn in the calibration background color.

I at least want the center hole to be smaller, but may make the main circle smaller too.
- [x] Find a reasonable value for `holesize`.
- [x] Adjust `diameter` as needed

**Comment by VPNLirvine** [comment]
Addressed by commit [84dab4f](https://github.com/VPNLirvine/trEYEcopa/commit/84dab4f3d2c045cce38e56c3b279a1712c4032b3)
