### ISSUE TITLE
Add one or two short breaks

### ISSUE THREAD

**Issue by brandonhackney** [VPNLirvine/trEYEcopa#21]
Sajjad said that blasting through all 100 videos in one sitting was really fatiguing, and that it might be good to have an enforced break or two in the middle of the experiment to let your eyes relax.
Please add an interrupt function that takes the trial number and total number of trials as input, determines whether to interrupt based on a ratio (e.g. 1/2 or 1/3), and then displays a screen saying something like "please take a moment to relax, press the X key when you're ready to continue."
Avoid using the space bar, escape key, or enter key, as these are already used by the eyetracker for various functions e.g. recalibration. Maybe make it only accept e.g. the number 3 as input so you can't accidentally blow past it.
Add an enforced timeout so you can't wait forever, and maybe a timer that warns you how long you have.
Then ensure you can easily enter recalibration if the apparatus needs to be adjusted e.g. to loosen the headband.

**Comment by VPNLirvine** [comment]
Resolved by pull request #22
