### ISSUE TITLE
Ensure we can run and analyze the TriCopa videos

### ISSUE THREAD

**Issue by brandonhackney** [VPNLirvine/trEYEcopa#3]
I know this repo is called trEYEcopa in reference to TriCopa, but the original code was actually written to handle the Martin & Weisberg videos. It's currently unclear whether 1. we can properly run the experiment with the TriCopa videos, or 2. whether we can properly analyze data generated from the TriCopa experiment.

- [x] Figure out which of the million functions in this repo actually runs the experiment
- [x] Check the existing experiment script to see if it allows TriCopa or if it's hardcoded for MW
- [x] If there _is_ a TriCopa option, ensure it works. Fix it if it doesn't.
- [x] If there's no TriCopa option at all, write one. (Likely solution is do a switch-case for MW or Tri)
- [x] Delete any floaters that don't support the experiment or analysis

**Comment by brandonhackney** [comment]
`Main_TriCopa_eyetracking` is the function that should run the experiment.
It is currently set to just loop through a list of stims pulled from `base/stims/*.mov`, without regard to any subfolders, mirroring, or other conditions.

**Comment by VPNLirvine** [comment]
`Main_TriCopa_eyetracking` does not run as-is, even on the originating computer. It also doesn't look like it implements any eyetracking functions. I'm pushing in a second function that DOES run, but isn't tuned for TriCOPA. Will start weaving the two together.

**Comment by brandonhackney** [comment]
The new main function is `Main_EyeLink.m`. I renamed `Main_TriCopa_eyetracking` to `old_tricopa.m` but am leaving it in because it still has some BIDS-related code like getting and exporting responses that I want to incorporate later.

**Comment by brandonhackney** [comment]
- [ ] Tick this box and close the issue when we've determined we can delete `old_tricopa.m`

**Comment by brandonhackney** [comment]
Code executes successfully as of [this commit](https://github.com/VPNLirvine/trEYEcopa/commit/f5ecede42f7579a5b1c0816e8b88abd91c286c07)
