### ISSUE TITLE
Better dependency implementation?

### ISSUE THREAD

**Issue by brandonhackney** [VPNLirvine/trEYEcopa#4]
Our two major dependencies are the TriCopa videos and the EDF file importer, which both currently exist as just downloaded files, as if we had made them ourselves. But they are both github repos that could potentially receive updates in the future. So what's the best way to handle that? Should we clone them into this repo?

**Comment by VPNLirvine** [comment]
I'll add that including the videos in the repo significantly slows down the time to push updates, so we should consider kicking them over to OSF.
Sajjad also mentioned that he customized some videos by e.g. flipping their orientation, so maybe calling the tricopa repo directly isn't the best idea anyway.

**Comment by VPNLirvine** [comment]
Videos were customized anyway, so I removed the old TriCOPA folder and added a link to where we're keeping the stimuli on OSF
re edfImport, there is a thing called [git submodules](https://www.atlassian.com/git/tutorials/git-submodule), but the very top of the page says "yeah or you could just copy the code straight in". As long as we cite the guy, it's probably ok.
